### ISSUE TITLE
可能需要保留Apache LICENSE 2.0

### ISSUE THREAD

**Issue by 1939323749** [tsurumi-yizhou/JiShi-Android#1]
`me.yihtseu.jishi.utils.DesEncryptUtils`是否使用了来自[Library-One-Tap-Android](https://github.com/qhy040404/Library-One-Tap-Android/tree/41e1ea711632bb657ff26161f9b833da27f1c4eb)的代码?如果是,请对该部分应用Apache LICENSE 2.0

**Comment by tsurumi-yizhou** [comment]
> `me.yihtseu.jishi.utils.DesEncryptUtils`是否使用了来自[Library-One-Tap-Android](https://github.com/qhy040404/Library-One-Tap-Android/tree/41e1ea711632bb657ff26161f9b833da27f1c4eb)的代码?如果是,请对该部分应用Apache LICENSE 2.0

确实是，稍后我会在源代码文件中补上许可证和来源，并在readme中提及。

**Comment by tsurumi-yizhou** [comment]
感谢您的提醒！
